<?php
/**
 * @file
 * Functions to support theming in the custom_theme theme.
 */

/**
 * Implements hook_theme_suggestions_page_alter.
 */

function custom_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {

  $current_path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  if ($alias === '/custom-render') {
    $suggestions[] = 'page__custom_render';
  }
}

/**
 * Implements hook_preprocess_html().
 */
function custom_theme_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  
  if ($alias === '/custom-render') {
    $variables['attributes']['class'] = 'custom-render';
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function custom_theme_theme_suggestions_node_alter(&$suggestions, $variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  
  if ($alias === '/custom-render') {
    $suggestions[] = 'node__custom_render';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_theme_preprocess_node(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  if ($alias === '/custom-render') {
    $variables['colors'] = 'red';
  }
}
